### ISSUE TITLE
Det verkar som att inget är public i lib.rs

### ISSUE THREAD

**Issue by PumpedSardines** [INDA23PlusPlus/arjon-chessapi#1]
Försöker importera ditt paket men den hittar inga funktioner. Tror du moste skriva pub före din mod och funktioner!

**Comment by arvidjonasson** [comment]
Sorry, skall fixa.

**Comment by arvidjonasson** [comment]
Fel knapp....

**Comment by arvidjonasson** [comment]
Fixat
